import { BarChart3, Database, KeyRound, LineChart, Settings2, SlidersHorizontal } from "lucide-react"
import { useEffect, useMemo, useState } from "react"
import { Card, CardContent } from "./components/ui/card"

type Assessment = { date: string; version: number; assessment: { metrics: Array<{ key: string; label: string; score: number; detail: string }>; source_event_count: number } }
const pages = [{ href: "/capture", label: "数据采集", icon: Database }, { href: "/analysis", label: "数据解读", icon: BarChart3 }, { href: "/settings", label: "设置", icon: Settings2 }]
const date = () => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Shanghai" }).format(new Date())
async function api<T>(url: string, init?: RequestInit) { const r = await fetch(url, init); if (!r.ok) throw new Error(await r.text()); return r.json() as Promise<T> }

function Shell({ children }: { children: React.ReactNode }) {
  const path = window.location.pathname === "/" ? "/capture" : window.location.pathname
  return <div className="min-h-screen bg-zinc-50 text-zinc-950"><header className="border-b border-zinc-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4"><a href="/capture" className="font-semibold tracking-tight">MirrorMe</a><nav className="flex gap-1">{pages.map(({ href, label, icon: Icon }) => <a key={href} href={href} className={`flex items-center gap-2 rounded-lg px-3 py-2 text-sm ${path === href ? "bg-zinc-950 text-white" : "text-zinc-500 hover:bg-zinc-100"}`}><Icon size={15} />{label}</a>)}</nav></div></header><main className="mx-auto max-w-6xl px-6 py-10">{children}</main></div>
}

function Capture() {
  const [daily, setDaily] = useState(date()); const [events, setEvents] = useState<Array<{ id: string; created_at: string; redacted: string; project: string | null; tags: string[]; is_private: boolean }>>([]); const [cleaned, setCleaned] = useState(""); const [documentId, setDocumentId] = useState(""); const [message, setMessage] = useState("选择日期后读取数据")
  const load = async () => { const rows = await api<typeof events>(`/api/events?date=${daily}&include_private=1`); setEvents(rows) }
  useEffect(() => { void load() }, [daily])
  const cleanDaily = async () => { const api_url = sessionStorage.getItem("llm_url") || ""; const api_key = sessionStorage.getItem("llm_key") || ""; const model = sessionStorage.getItem("llm_model") || ""; const prompt = sessionStorage.getItem("llm_prompt") || ""; setMessage("正在合并并清洗当天公开事件"); const result = await api<{ output: string; source_event_count: number; composed_event_count: number; document: { id: string } }>("/api/daily/llm-clean", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ date: daily, api_url, api_key, model, prompt }) }); setCleaned(result.output); setDocumentId(result.document.id); setMessage(`已将 ${result.source_event_count} 条原始提交合并为 ${result.composed_event_count} 段，再保存清洗草稿`) }
  const accept = async () => { if (!documentId) return; await api(`/api/cleaned-documents/${documentId}/accept`, { method: "POST", headers: { "Content-Type": "application/json" }, body: "{}" }); setMessage("已接受此清洗版本，并生成状态观测") }
  const observe = async () => { await api("/api/state-assessments/daily", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ date: daily }) }); setMessage("已生成并留存当日状态观测") }
  return <Shell><p className="text-xs font-semibold uppercase tracking-[.15em] text-emerald-700">Capture & process</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">先整理当天数据，<br />再把它交给分析。</h1><div className="mt-8 grid gap-4 lg:grid-cols-[1.3fr_.7fr]"><Card><CardContent><div className="flex items-center justify-between"><p className="text-sm font-medium">{daily} 的数据库数据</p><span className="text-xs text-zinc-500">{events.length} 条</span></div><div className="mt-4 max-h-80 overflow-auto">{events.map(event => <article key={event.id} className="border-t border-zinc-100 py-3"><p className="text-xs text-zinc-500">{event.created_at.slice(11, 19)} · {event.project || "未归档"} · {event.is_private ? "私密" : "公开"}</p><p className="mt-1 text-sm leading-6">{event.redacted}</p></article>) || <p className="text-sm text-zinc-500">没有数据</p>}</div></CardContent></Card><div className="grid gap-4"><Card><CardContent><p className="text-sm font-medium">选择日期</p><input value={daily} onChange={e => setDaily(e.target.value)} type="date" className="mt-4 w-full rounded-lg border border-zinc-200 p-2" /><button onClick={() => void cleanDaily()} className="mt-4 w-full rounded-lg bg-zinc-950 px-3 py-2 text-sm text-white">LLM 清洗当天数据</button><p className="mt-2 text-xs leading-5 text-zinc-500">仅发送公开事件。推荐使用本地 LLM 进行清洗。</p><button onClick={() => void observe()} className="mt-3 w-full rounded-lg border border-zinc-300 px-3 py-2 text-sm">直接按原始数据观测</button></CardContent></Card><details className="rounded-xl border border-zinc-200 bg-white p-5"><summary className="cursor-pointer text-sm font-medium">手动补充当天内容</summary><p className="mt-2 text-sm text-zinc-500">低频使用。</p></details></div></div>{cleaned && <Card className="mt-4"><CardContent><div className="flex items-center justify-between"><p className="text-sm font-medium">清洗草稿，可分析文本</p><button onClick={() => void accept()} className="rounded-lg bg-zinc-950 px-3 py-2 text-sm text-white">接受此版本并生成观测</button></div><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-zinc-700">{cleaned}</p></CardContent></Card>}<p className="mt-4 text-sm text-zinc-500">{message}</p></Shell>
}

function Analysis() {
  const [records, setRecords] = useState<Assessment[]>([]); const [loading, setLoading] = useState(true)
  useEffect(() => { api<Assessment[]>("/api/state-assessments?latest_per_day=1&limit=30").then(setRecords).finally(() => setLoading(false)) }, [])
  const metrics = useMemo(() => records.at(-1)?.assessment.metrics || [], [records]); const width = 700; const height = 220
  const line = (key: string) => records.map((record, i) => { const score = record.assessment.metrics.find(m => m.key === key)?.score ?? 0; const x = records.length === 1 ? width / 2 : i * width / (records.length - 1); return `${x},${height - score * 1.7}` }).join(" ")
  return <Shell><p className="text-xs font-semibold uppercase tracking-[.15em] text-emerald-700">Interpret & analyze</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">用连续曲线，<br />解读表达背后的变化。</h1>{loading ? <p className="mt-10 text-zinc-500">读取观测数据中</p> : !records.length ? <Card className="mt-8"><CardContent><p className="font-medium">还没有状态观测</p><p className="mt-2 text-sm text-zinc-500">前往数据采集页，选择日期后留存一次观测。</p></CardContent></Card> : <><Card className="mt-8"><CardContent><div className="flex items-center justify-between"><div><p className="text-sm font-medium">多维观察曲线</p><p className="mt-1 text-sm text-zinc-500">最近 {records.length} 天，每日采用最新观测</p></div><LineChart className="text-emerald-700" /></div><svg viewBox={`0 0 ${width} ${height}`} className="mt-6 w-full overflow-visible" role="img" aria-label="状态维度观察曲线"><line x1="0" y1={height} x2={width} y2={height} stroke="#e4e4e7" />{metrics.slice(0, 3).map((metric, index) => <polyline key={metric.key} points={line(metric.key)} fill="none" stroke={["#18181b", "#059669", "#d97706"][index]} strokeWidth="3" />)}</svg><div className="mt-4 flex flex-wrap gap-4">{metrics.slice(0, 3).map((m, i) => <span key={m.key} className="text-xs text-zinc-500"><i className="mr-2 inline-block h-2 w-2 rounded-full" style={{ background: ["#18181b", "#059669", "#d97706"][i] }} />{m.label}</span>)}</div></CardContent></Card><section className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{metrics.map(metric => <Card key={metric.key}><CardContent><p className="text-sm text-zinc-500">{metric.label}</p><strong className="mt-3 block text-4xl">{metric.score}</strong><p className="mt-3 text-sm text-zinc-500">{metric.detail}</p></CardContent></Card>)}</section></>}</Shell>
}

function Settings() { const [url, setUrl] = useState(sessionStorage.getItem("llm_url") || ""); const [model, setModel] = useState(sessionStorage.getItem("llm_model") || ""); const [key, setKey] = useState(sessionStorage.getItem("llm_key") || ""); const [prompt, setPrompt] = useState(sessionStorage.getItem("llm_prompt") || "只输出清洗后的原文。保留原意、事实、专有名词、数字和不确定性；修正明显空白、断句、重复片段、填充词和标点。不要总结、扩写或编造。"); const save = () => { sessionStorage.setItem("llm_url", url); sessionStorage.setItem("llm_model", model); sessionStorage.setItem("llm_key", key); sessionStorage.setItem("llm_prompt", prompt) }; return <Shell><p className="text-xs font-semibold uppercase tracking-[.15em] text-emerald-700">Rules & API</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">设置规则，<br />再决定如何处理数据。</h1><div className="mt-8 grid gap-4 lg:grid-cols-2"><Card><CardContent><KeyRound /><h2 className="mt-4 font-medium">LLM API 与提示词</h2><div className="mt-4 grid gap-3"><input value={url} onChange={e => setUrl(e.target.value)} className="rounded-lg border border-zinc-200 p-3" placeholder="API URL" /><input value={model} onChange={e => setModel(e.target.value)} className="rounded-lg border border-zinc-200 p-3" placeholder="Model" /><input value={key} onChange={e => setKey(e.target.value)} type="password" className="rounded-lg border border-zinc-200 p-3" placeholder="API Key（仅当前浏览器会话）" /><textarea value={prompt} onChange={e => setPrompt(e.target.value)} rows={8} className="rounded-lg border border-zinc-200 p-3" placeholder="LLM 清洗提示词" /></div><button onClick={save} className="mt-4 rounded-lg bg-zinc-950 px-4 py-2 text-sm text-white">保存会话设置</button></CardContent></Card><Card><CardContent><SlidersHorizontal /><h2 className="mt-4 font-medium">处理规则</h2><label className="mt-5 flex items-center justify-between text-sm"><span>移除完全重复的相邻句子</span><input type="checkbox" defaultChecked /></label><label className="mt-5 flex items-center justify-between text-sm"><span>状态评估仅使用公开事件</span><input type="checkbox" defaultChecked /></label><p className="mt-6 text-sm leading-6 text-zinc-500">提示词和 API 配置保存于当前浏览器会话；API Key 不写入 SQLite。</p></CardContent></Card></div></Shell> }
export default function App() { const path = window.location.pathname; return path === "/analysis" || path === "/state" ? <Analysis /> : path === "/settings" ? <Settings /> : <Capture /> }
